main:
  - name: Recensioner
    url: '/category/review/'
    weight: 10
  - name: Forex mäklare
    url: '/category/forex-broker/'
    weight: 20
  - name: Autotrading
    url: '/category/autotrader/'
    weight: 30
  - name: Ponzibedrägerier
    url: '/category/ponzi/'
    weight: 40
  - name: Rekommendationer
    url: '/category/recommendation/'
    weight: 50