main:
  - name: Opiniões
    url: '/category/review/'
    weight: 10
  - name: Corretor Forex
    url: '/category/forex-broker/'
    weight: 20
  - name: Auto-trading
    url: '/category/autotrader/'
    weight: 30
  - name: Esquemas Ponzi
    url: '/category/ponzi/'
    weight: 40
  - name: Recomendações
    url: '/category/recommendation/'
    weight: 50