main:
  - name: Recenzii
    url: '/category/review/'
    weight: 10
  - name: Broker Forex
    url: '/category/forex-broker/'
    weight: 20
  - name: Autotrading
    url: '/category/autotrader/'
    weight: 30
  - name: Scheme Ponzi
    url: '/category/ponzi/'
    weight: 40
  - name: Recomandări
    url: '/category/recommendation/'
    weight: 50