main:
  - name: Opiniones
    url: '/category/review/'
    weight: 10
  - name: Corredor de divisas
    url: '/category/forex-broker/'
    weight: 20
  - name: Autotrading
    url: '/category/autotrader/'
    weight: 30
  - name: Esquemas Ponzi
    url: '/category/ponzi/'
    weight: 40
  - name: Recomendaciones
    url: '/category/recommendation/'
    weight: 50