main:
  - name: Recenzie
    url: '/category/review/'
    weight: 10
  - name: Forex Broker
    url: '/category/forex-broker/'
    weight: 20
  - name: Autotrading
    url: '/category/autotrader/'
    weight: 30
  - name: Ponziho schémy
    url: '/category/ponzi/'
    weight: 40
  - name: Odporúčania
    url: '/category/recommendation/'
    weight: 50